object puzzle extends App {
  val (aWords, gWords, sWords, targets) = getWords
  val space = aWords.length * gWords.length * sWords.length
  var i = 0
  for (aWord <- aWords;
       gWord <- gWords;
       sWord <- sWords) {
    i += 1
    if (i % 1000000 == 0) {
      printf("%1.3f: On %d (%1.1f%%)\n", 0.001 * (System.currentTimeMillis - executionStart), i, 100.0 * i / space)
    }
    val downWords = rotateWords(Vector("newt", aWord, gWord, sWord)) 
    if (downWords.forall(targets.contains(_)) && (Set[Char]() ++ downWords.mkString.toSeq).size == 16) {
      println("Solution:")
      downWords.foreach(println)
      println()
    }
  }

  def rotateWords(words: Vector[String]): Seq[String] = 0.until(4).map(i => words.map(_(i)).mkString)
  // Swiped from http://www.morewords.com/
  def getWords = {
    val aWords = "aahs aals abas abba abbe abed abet able ably abos abri abut abye abys aced aces ache achy acid acme acne acre acta acts acyl adds adit ados adze aeon aero aery afar agar agas aged agee ager ages agha agin agio agly agma agog agon ague ahem ahoy aide aids ails aims ains airn airs airt airy aits ajar ajee akee akin alae alan alar alas alba albs alec alee alef ales alfa alga alif alit alky alls ally alma alme alms aloe alow alps also alto alts alum amah amas ambo amen amia amid amie amin amir amis ammo amok amps amus amyl anal anas ands anes anew anga anil anis ankh anna anoa anon ansa anta ante anti ants anus aped aper apes apex apod apse aqua arak arbs arch arco arcs area ares arfs aria arid aril arks arms army arse arts arty arum arvo aryl asci asea ashy asks asps atap ates atma atom atop auks auld aunt aura auto aver aves avid avos avow away awed awee awes awls awns awny awol awry axal axed axel axes axil axis axle axon ayah ayes ayin azan azon".split(' ')
    val gWords = "gabs gaby gadi gads gaed gaen gaes gaff gaga gage gags gain gait gala gale gall gals gama gamb game gamp gams gamy gane gang gaol gape gaps gapy garb gars gash gasp gast gate gats gaud gaum gaun gaur gave gawk gawp gays gaze gear geck geds geed geek gees geez geld gels gelt gems gene gens gent genu germ gest geta gets geum ghat ghee ghis gibe gibs gids gied gien gies gift giga gigs gild gill gilt gimp gink gins gips gird girl girn giro girt gist gits give glad gled glee gleg glen gley glia glib glim glob glom glop glow glue glug glum glut gnar gnat gnaw gnus goad goal goas goat gobo gobs goby gods goer goes gogo gold golf gone gong good goof gook goon goop goos gore gorp gory gosh gout gowd gowk gown goys grab grad gram gran grat gray gree grew grey grid grig grim grin grip grit grog grot grow grub grue grum guan guar guck gude guff guid gulf gull gulp guls gums gunk guns guru gush gust guts guvs guys gybe gyms gyps gyre gyri gyro gyve".split(' ')
    val sWords = "sabe sabs sack sacs sade sadi safe saga sage sago sags sagy said sail sain sake saki sale sall salp sals salt same samp sand sane sang sank sans saps sard sari sark sash sass sate sati saul save sawn saws says scab scad scag scam scan scar scat scop scot scow scry scud scum scup scut seal seam sear seas seat secs sect seed seek seel seem seen seep seer sees sego segs seif seis self sell sels seme semi send sene sent sept sera sere serf sers seta sets sett sewn sews sext sexy shad shag shah sham shat shaw shay shea shed shes shew shim shin ship shit shiv shmo shod shoe shog shoo shop shot show shri shul shun shut sial sibb sibs sice sick sics side sift sigh sign sike sild silk sill silo silt sima simp sims sine sing sinh sink sins sipe sips sire sirs site sith sits size sizy skag skas skat skee skeg skep skew skid skim skin skip skis skit skua slab slag slam slap slat slaw slay sled slew slid slim slip slit slob sloe slog slop slot slow slub slue slug slum slur slut smew smit smog smug smut snag snap snaw sned snib snip snit snob snog snot snow snub snug snye soak soap soar sobs sock soda sods sofa soft soil soja soke sola sold sole soli solo sols soma some sone song sons sook soon soot soph sops sora sorb sord sore sori sorn sort soth sots souk soul soup sour sous sown sows soya soys spae spam span spar spas spat spay spaz spec sped spew spic spik spin spit spiv spot spry spud spue spun spur sris stab stag star stat staw stay stem step stet stew stey stir stoa stob stop stow stub stud stum stun stye suba subs such suck sudd suds sued suer sues suet sugh suit sulk sulu sumo sump sums sung sunk sunn suns supe sups suqs sura surd sure surf suss swab swag swam swan swap swat sway swig swim swob swop swot swum sybo syce syke syli sync syne syph".split(' ')
    val targets = collection.SortedSet[String]() ++ List(
      "nags",
      "each earl earn ears ease east easy eath eats eaux eave ebbs ebon eche echo ecru ecus eddo eddy edge edgy edhs edit eels eely eery effs efts egad egal eger eggs eggy egis egos eide eked ekes elan elds elhi elks ells elms elmy else emes emeu emfs emic emir emit emus emyd ends engs enol enow envy eons epee epha epic epos eras ergo ergs erne erns eros errs erst eses espy etas etch eths etic etna etui euro even ever eves evil ewer ewes exam exec exes exit exon expo eyas eyed eyen eyer eyes eyne eyra eyre eyry",
      "wabs wack wade wadi wads wady waes waff waft wage wags waif wail wain wair wait wake wale walk wall waly wame wand wane wans want wany waps ward ware wark warm warn warp wars wart wary wash wasp wast wats watt wauk waul waur wave wavy wawl waws waxy ways weak weal wean wear webs weds weed week weel ween weep weer wees weet weft weir weka weld well welt wend wens went wept were wert west wets wham whap what whee when whet whew whey whid whig whim whin whip whir whit whiz whoa whom whop whys wich wick wide wife wigs wild wile will wilt wily wimp wind wine wing wink wino wins winy wipe wire wiry wise wish wisp wiss wist wite with wits wive woad woes wogs woke woks wold wolf womb wonk wons wont wood woof wool woos wops word wore work worm worn wort wost wots wove wows wrap wren writ wuss wych wyes wyle wynd wynn wyns wyte",
      "tabs tabu tace tach tack taco tact tads tael tags tahr tail tain taka take tala talc tale tali talk tall tame tamp tams tang tank tans taos tapa tape taps tare tarn taro tarp tars tart task tass tate tats taus taut tavs taws taxa taxi teak teal team tear teas teat teds teed teel teem teen tees teff tegs tela tele tell tels temp tend tens tent tepa term tern test teth tets tews text thae than that thaw thee them then thew they thin thio thir this thou thro thru thud thug thus tick tics tide tidy tied tier ties tiff tike tiki tile till tils tilt time tine ting tins tint tiny tipi tips tire tirl tiro titi tits tivy toad toby tods tody toea toed toes toff toft tofu toga togs toil toit toke tola told tole toll tolu tomb tome toms tone tong tons tony took tool toom toon toot tope toph topi tops tora torc tore tori torn toro torr tors tort tory tosh toss tost tote tots tour tout town tows towy toyo toys trad tram trap tray tree tref trek tret trey trig trim trio trip trod trop trot trow troy true trug tsar tsks tuba tube tubs tuck tufa tuff tuft tugs tuis tule tump tuna tune tung tuns tups turd turf turk turn tush tusk tuts tutu twae twas twat twee twig twin twit twos tyee tyer tyes tyin tyke tyne type typo typp typy tyre tyro tzar").flatMap(_.split(' '))
    (aWords, gWords, sWords, targets)
  }
}
